version: "3.9"

services:
  pgdatabase:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - local_net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8091:80
    networks:
      - local_net
  keycloak:
    image: quay.io/keycloak/keycloak
    command: ['start-dev']
    depends_on:
      - pgdatabase
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: local_postgres
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8180:8080
      - 8787:8787 
    networks:
      - local_net
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - local_net
  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - 5701:5701
  hz-management-center:
    image: hazelcast/management-center:latest-snapshot
    ports:
      - 8099:8080
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hazelcast
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log_data:/var/log/rabbitmq
    networks:
      - local_net
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - local_net

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - local_net
    depends_on:
      - redis

  config-server:
    image: mihriban/config-server:v1.0.0
    container_name: config-server-test
    depends_on:
      - postgres
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8888:8888"
    networks:
      - local_net

  user-service:
    image: mihriban/user-service:v1.0.0
    container_name: user-service-test
    depends_on:
      - postgres
      - redis
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_REDIS_HOST: redis
    ports:
      - "9091:9091"
    networks:
      - local_net

  auth-service:
    image: mihriban/auth-service:v1.0.0
    container_name: auth-service-test
    depends_on:
      - mongo
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_MONGO_URI: mongodb://root:rootpass@mongo:27017/admin
    ports:
      - "9099:9099"
    networks:
      - local_net

volumes:
  mongo_data:
  postgres_data:
    external: true
  rabbitmq_data:
    external: true
  rabbitmq_log_data:
    external: true
  redis_data:
    external: true


networks:
  local_net:
    driver: bridge



