version: "3.9"

services:
  pgdatabase:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - local_net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8091:80
    networks:
      - local_net
  keycloak:
    image: quay.io/keycloak/keycloak
    command: ['start-dev']
    depends_on:
      - pgdatabase
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: local_postgres
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8180:8080
      - 8787:8787 
    networks:
      - local_net
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - local_net
  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - 5701:5701
  hz-management-center:
    image: hazelcast/management-center:latest-snapshot
    ports:
      - 8099:8080
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hazelcast
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log_data:/var/log/rabbitmq
    networks:
      - local_net
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - local_net

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - local_net
    depends_on:
      - redis

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


volumes:
  mongo_data:
  postgres_data:
    external: true
  rabbitmq_data:
    external: true
  rabbitmq_log_data:
    external: true
  redis_data:
    external: true
  jenkins_home:


networks:
  local_net:
    driver: bridge



