server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mihribanutanc/sosyal-media-config-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "mihribanutanc"
          password: ${GIT_KEY}